"""add_quiz_fk

Revision ID: f560bd581097
Revises: 63fbe58f91ef
Create Date: 2026-04-11 21:59:47.023779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f560bd581097'
down_revision: Union[str, Sequence[str], None] = '63fbe58f91ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_quiz_questions_referendum_id', 'referendums', ['referendum_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_questions_referendum_id', type_='foreignkey')

    # ### end Alembic commands ###
